xcodeproj 'QuadernoKit Tests'
workspace '../QuadernoKit'
inhibit_all_warnings!

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'

  pod 'OCMock', '~> 2.2.1'
  pod 'Expecta', '~> 0.2.1'
  pod 'QuadernoKit', :path => '../'
end